<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="28.398999999999997" tests="18" failures="12" skipped="3">
  <testsuite name="Root Suite" timestamp="2020-06-02T17:30:29" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Community Profile Sections" timestamp="2020-06-02T17:30:29" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="in mobile" timestamp="2020-06-02T17:30:29" tests="6" failures="4" time="11.325">
    <testcase name="Community Profile Sections in mobile Should see details" time="0" classname="Should see details">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in mobile should be able to save and remove community" time="0" classname="should be able to save and remove community">
      <failure message="Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: &apos;postUserSaves&apos;. No request ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'postUserSaves'. No request ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in mobile should request pricing from section" time="11.325" classname="should request pricing from section">
    </testcase>
    <testcase name="Community Profile Sections in mobile should show and request care services" time="0" classname="should show and request care services">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in mobile should show and request amenities" time="0" classname="should show and request amenities">
      <failure message="Invalid attempt to spread non-iterable instance" type="TypeError"><![CDATA[TypeError: Invalid attempt to spread non-iterable instance
    at http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9651
    at u (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9716)
    at Context.<anonymous> (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:16263)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in tablet" timestamp="2020-06-02T17:32:09" tests="6" failures="4" time="8.109">
    <testcase name="Community Profile Sections in tablet Should see details" time="0" classname="Should see details">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in tablet should be able to save and remove community" time="0" classname="should be able to save and remove community">
      <failure message="Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: &apos;postUserSaves&apos;. No request ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'postUserSaves'. No request ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in tablet should request pricing from section" time="8.109" classname="should request pricing from section">
    </testcase>
    <testcase name="Community Profile Sections in tablet should show and request care services" time="0" classname="should show and request care services">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in tablet should show and request amenities" time="0" classname="should show and request amenities">
      <failure message="Invalid attempt to spread non-iterable instance" type="TypeError"><![CDATA[TypeError: Invalid attempt to spread non-iterable instance
    at http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9651
    at u (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9716)
    at Context.<anonymous> (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:16263)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in laptop" timestamp="2020-06-02T17:33:38" tests="6" failures="4" time="8.965">
    <testcase name="Community Profile Sections in laptop Should see details" time="0" classname="Should see details">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in laptop should be able to save and remove community" time="0" classname="should be able to save and remove community">
      <failure message="Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: &apos;postUserSaves&apos;. No request ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'postUserSaves'. No request ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in laptop should request pricing from section" time="8.965" classname="should request pricing from section">
    </testcase>
    <testcase name="Community Profile Sections in laptop should show and request care services" time="0" classname="should show and request care services">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Community Profile Sections in laptop should show and request amenities" time="0" classname="should show and request amenities">
      <failure message="Invalid attempt to spread non-iterable instance" type="TypeError"><![CDATA[TypeError: Invalid attempt to spread non-iterable instance
    at http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9651
    at u (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:9716)
    at Context.<anonymous> (http://www.lvh.me/__cypress/tests?p=cypress/integration/profilePage/communityProfileSections.spec.js-409:1:16263)]]></failure>
    </testcase>
  </testsuite>
</testsuites>