<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="12" failures="12">
  <testsuite name="Root Suite" timestamp="2020-06-02T17:42:47" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Sending Referral to Agent" timestamp="2020-06-02T17:42:47" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="in mobile" timestamp="2020-06-02T17:42:47" tests="4" failures="4" time="0">
    <testcase name="Sending Referral to Agent in mobile Creating Lead - Lead Conversion on Get Pricing flow" time="0" classname="Creating Lead - Lead Conversion on Get Pricing flow">
      <failure message="Timed out retrying: Expected to find content: &apos;1 - 3 months&apos; within the element: [ &lt;div#app&gt;, 563 more... ] but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: '1 - 3 months' within the element: [ <div#app>, 563 more... ] but never did.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in mobile Logging in to Admin Account" time="0" classname="Logging in to Admin Account">
      <failure message="Timed out retrying: Expected to find element: &apos;form input[name=&quot;emailOrPhone&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'form input[name="emailOrPhone"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in mobile Logging in to Agent Account" time="0" classname="Logging in to Agent Account">
      <failure message="Timed out retrying: Expected to find content: &apos;Log Out&apos; within the element: [ &lt;a.Link__StyledLink-sc-1r2nabr-1.cddxbq&gt;, 169 more... ] but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'Log Out' within the element: [ <a.Link__StyledLink-sc-1r2nabr-1.cddxbq>, 169 more... ] but never did.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in mobile Accepting Referral" time="0" classname="Accepting Referral">
      <failure message="Timed out retrying: Expected to find element: &apos;span[data-cy=&quot;menu&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'span[data-cy="menu"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in tablet" timestamp="2020-06-02T17:43:15" tests="4" failures="4" time="0">
    <testcase name="Sending Referral to Agent in tablet Creating Lead - Lead Conversion on Get Pricing flow" time="0" classname="Creating Lead - Lead Conversion on Get Pricing flow">
      <failure message="Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It&apos;s possible to enable debugging these scripts by adding the &apos;crossorigin&apos; attribute and setting a CORS header.

https://on.cypress.io/cross-origin-script-error

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the &apos;uncaught:exception&apos; event.

https://on.cypress.io/uncaught-exception-from-application" type="Uncaught Error"><![CDATA[Uncaught Error: Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the 'crossorigin' attribute and setting a CORS header.

https://on.cypress.io/cross-origin-script-error

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at createErrFromMsg (http://www.lvh.me/__cypress/runner/cypress_runner.js:94235:14)
    at Object.createUncaughtException (http://www.lvh.me/__cypress/runner/cypress_runner.js:94240:13)
    at Object.onUncaughtException (http://www.lvh.me/__cypress/runner/cypress_runner.js:101011:20)
    at onError (http://www.lvh.me/__cypress/runner/cypress_runner.js:100234:39)
    at sendEvent (http://www.lvh.me/__cypress/runner/cypress_runner.js:96334:30)
    at sendMouseEvent (http://www.lvh.me/__cypress/runner/cypress_runner.js:96356:10)
    at sendClick (http://www.lvh.me/__cypress/runner/cypress_runner.js:96416:10)
    at Object._mouseClickEvents (http://www.lvh.me/__cypress/runner/cypress_runner.js:96223:19)
    at Object.click (http://www.lvh.me/__cypress/runner/cypress_runner.js:96148:36)
    at onReady (http://www.lvh.me/__cypress/runner/cypress_runner.js:86627:35)
    at onReady (http://www.lvh.me/__cypress/runner/cypress_runner.js:86579:30)
    at runAllChecks (http://www.lvh.me/__cypress/runner/cypress_runner.js:85227:14)
    at retryActionability (http://www.lvh.me/__cypress/runner/cypress_runner.js:85235:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in tablet Logging in to Admin Account" time="0" classname="Logging in to Admin Account">
      <failure message="Timed out retrying: Expected to find element: &apos;form input[name=&quot;emailOrPhone&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'form input[name="emailOrPhone"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in tablet Logging in to Agent Account" time="0" classname="Logging in to Agent Account">
      <failure message="Timed out retrying: Expected to find content: &apos;Log Out&apos; within the element: [ &lt;a.Link__StyledLink-sc-1r2nabr-1.cddxbq&gt;, 169 more... ] but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'Log Out' within the element: [ <a.Link__StyledLink-sc-1r2nabr-1.cddxbq>, 169 more... ] but never did.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in tablet Accepting Referral" time="0" classname="Accepting Referral">
      <failure message="Timed out retrying: Expected to find element: &apos;span[data-cy=&quot;menu&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'span[data-cy="menu"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in laptop" timestamp="2020-06-02T17:43:39" tests="4" failures="4" time="0">
    <testcase name="Sending Referral to Agent in laptop Creating Lead - Lead Conversion on Get Pricing flow" time="0" classname="Creating Lead - Lead Conversion on Get Pricing flow">
      <failure message="Timed out retrying: Expected to find content: &apos;1 - 3 months&apos; within the element: [ &lt;div#app&gt;, 563 more... ] but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: '1 - 3 months' within the element: [ <div#app>, 563 more... ] but never did.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in laptop Logging in to Admin Account" time="0" classname="Logging in to Admin Account">
      <failure message="Timed out retrying: Expected to find element: &apos;form input[name=&quot;emailOrPhone&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'form input[name="emailOrPhone"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in laptop Logging in to Agent Account" time="0" classname="Logging in to Agent Account">
      <failure message="Timed out retrying: Expected to find content: &apos;Log Out&apos; within the element: [ &lt;a.Link__StyledLink-sc-1r2nabr-1.cddxbq&gt;, 169 more... ] but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'Log Out' within the element: [ <a.Link__StyledLink-sc-1r2nabr-1.cddxbq>, 169 more... ] but never did.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
    <testcase name="Sending Referral to Agent in laptop Accepting Referral" time="0" classname="Accepting Referral">
      <failure message="Timed out retrying: Expected to find element: &apos;span[data-cy=&quot;menu&quot;]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: 'span[data-cy="menu"]', but never found it.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at onFailFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:85591:16)
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137520:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://www.lvh.me/__cypress/runner/cypress_runner.js:134132:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134142:10)
    at Async.drainQueues (http://www.lvh.me/__cypress/runner/cypress_runner.js:134016:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>